name: Draft release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
          stable: true
      - run: make
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ./dns-inventory_*
