name: Draft release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
          stable: true
      - run: make
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ./dns-inventory_*
          fail_on_unmatched_files: true
